#!/bin/bash

# Script to generate build-info.properties with version and git information
# This script is called during the Maven build process

echo "🔧 Generating build information..."

# Get current directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Get git information
GIT_COMMIT_ID=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_ID_ABBREV=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_TIME=$(git log -1 --format=%ci 2>/dev/null || echo "unknown")

# Get current timestamp
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create build-info.properties
cat > build-info.properties << EOF
# Build information generated by Maven
app.version=1.2.0
build.timestamp=${BUILD_TIMESTAMP}
git.commit.id=${GIT_COMMIT_ID}
git.commit.id.abbrev=${GIT_COMMIT_ID_ABBREV}
git.branch=${GIT_BRANCH}
git.commit.time=${GIT_COMMIT_TIME}
maven.version=3.9.11
EOF

echo "✅ Build information generated successfully"
echo "📄 Generated build-info.properties:"
cat build-info.properties