#!/bin/bash
#
# oci8j-connector - Oracle 8i REST API
# Copyright (c) 2024 - 2026 Hermes Rodríguez
# SPDX-License-Identifier: MIT
#
# Script to generate build-info.properties with version and git information
#
echo "🔧 Generating build information..."

# Get current directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

# Get git information
GIT_COMMIT_ID=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_ID_ABBREV=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT_TIME=$(git log -1 --format=%ci 2>/dev/null || echo "unknown")

# Get version from pom.xml
APP_VERSION=$(grep -m1 '<version>' "${PROJECT_ROOT}/pom.xml" | sed 's/.*<version>\(.*\)<\/version>.*/\1/' | tr -d ' ')

# Get current timestamp
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create build-info.properties
cat > "${PROJECT_ROOT}/build-info.properties" << EOF
# Build information generated by Maven
app.version=${APP_VERSION}
build.timestamp=${BUILD_TIMESTAMP}
git.commit.id=${GIT_COMMIT_ID}
git.commit.id.abbrev=${GIT_COMMIT_ID_ABBREV}
git.branch=${GIT_BRANCH}
git.commit.time=${GIT_COMMIT_TIME}
maven.version=3.9.11
EOF

echo "✅ Build information generated successfully"
echo "📄 Generated build-info.properties:"
cat "${PROJECT_ROOT}/build-info.properties"