@echo off
REM
REM oci8j-connector - Oracle 8i REST API
REM Copyright (c) 2024 - 2026 Hermes Rodríguez
REM SPDX-License-Identifier: MIT
REM
REM Script to generate build-info.properties with version and git information
REM
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
set "PROJECT_ROOT=%SCRIPT_DIR%\.."

echo Generating build information...

set "GIT_COMMIT_ID=unknown"
set "GIT_COMMIT_ID_ABBREV=unknown"
set "GIT_BRANCH=unknown"
set "GIT_COMMIT_TIME=unknown"
set "APP_VERSION=0.0.0"

where git >nul 2>&1
if not errorlevel 1 (
  for /f "delims=" %%A in ('git -C "%PROJECT_ROOT%" rev-parse HEAD 2^>nul') do set "GIT_COMMIT_ID=%%A"
  for /f "delims=" %%A in ('git -C "%PROJECT_ROOT%" rev-parse --short HEAD 2^>nul') do set "GIT_COMMIT_ID_ABBREV=%%A"
  for /f "delims=" %%A in ('git -C "%PROJECT_ROOT%" rev-parse --abbrev-ref HEAD 2^>nul') do set "GIT_BRANCH=%%A"
  for /f "delims=" %%A in ('git -C "%PROJECT_ROOT%" log -1 --format^=%%ci 2^>nul') do set "GIT_COMMIT_TIME=%%A"
)

if exist "%PROJECT_ROOT%\pom.xml" (
  for /f "usebackq tokens=2 delims=<>" %%A in (`findstr /n /c:"<version>" "%PROJECT_ROOT%\pom.xml"`) do (
    if not defined _ver_done (
      set "APP_VERSION=%%A"
      set "_ver_done=1"
    )
  )
)

for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value 2^>nul') do set "DT=%%I"
if defined DT (
  set "BUILD_TIMESTAMP=%DT:~0,4%-%DT:~4,2%-%DT:~6,2%T%DT:~8,2%:%DT:~10,2%:%DT:~12,2%Z"
) else (
  set "BUILD_TIMESTAMP=unknown"
)

(
  echo # Build information generated by Maven
  echo app.version=%APP_VERSION%
  echo build.timestamp=%BUILD_TIMESTAMP%
  echo git.commit.id=%GIT_COMMIT_ID%
  echo git.commit.id.abbrev=%GIT_COMMIT_ID_ABBREV%
  echo git.branch=%GIT_BRANCH%
  echo git.commit.time=%GIT_COMMIT_TIME%
  echo maven.version=3.9.11
) > "%PROJECT_ROOT%\build-info.properties"

echo Build information generated successfully
echo Generated build-info.properties:
type "%PROJECT_ROOT%\build-info.properties"
exit /b 0
